### PR TITLE
core/maps allow excluding map IDs/UIDs

### PR DESCRIPTION
**Pull request by ezio416**

### CODE REVIEW

**Comment by codecat** [comment]
Shouldn't this be a different endpoint? Why should this be on this page?

**Comment by davidbmaier** [comment]
Ye, probably best to split this into two endpoints since the routes are different. We have a similar situation in the Live API, makes sense to keep it consistent here imo.

**Review by codecat — CHANGES_REQUESTED** [review]
This should be its own endpoint page.

**Comment by davidbmaier** [comment]
Done in https://github.com/openplanet-nl/nadeoapi-docs/commit/87a78c87937b57e458c3801e4b84e917c50fce8c

**Pull request closed without merging**
